
INSERT INTO contacting.survey_call_records(account_friendly_name,phone_num, survey_name, offered_datetime) VALUES ('NL', '+31687855555', 'nlsurvey1', 1642064183015);
INSERT INTO contacting.survey_call_records(account_friendly_name,phone_num, survey_name, offered_datetime) VALUES ('BE', '+31687855556', 'besurvey1', 1542064183015);
INSERT INTO contacting.survey_call_records(account_friendly_name,phone_num, survey_name, offered_datetime) VALUES ('NL', '+31687855555', 'nlsurvey2', 1642064183016);
INSERT INTO contacting.survey_call_records(account_friendly_name,phone_num, survey_name, offered_datetime) VALUES ('BE', '+31687855556', 'besurvey2', 1542064183016);
