--liquibase formatted sql

--changeset dinchand:connection_tables
CREATE TABLE CONNECTIONS (
	ID NUMBER(10,0),
	DOMAIN VARCHAR2(255 CHAR) NOT NULL,
	LAYER VARCHAR2(255 CHAR) NOT NULL,
	ACCOUNT_ID NUMBER(10,0) NOT NULL,
	PRIMARY KEY (ID)
);

CREATE TABLE CONNECTIONS_DETAILS (
 	ID NUMBER(10,0),
	CONNECTION_ID NUMBER(10,0) NOT NULL,
	CONNECTION_TYPE VARCHAR2(255 CHAR) NOT NULL,
	EDGE_LOCATION VARCHAR2(255 CHAR) NOT NULL,
	URL VARCHAR2(1000 CHAR) NOT NULL,
	PRIMARY KEY (ID),
	CONSTRAINT fk_cd_connection
        FOREIGN KEY (CONNECTION_ID)
        REFERENCES CONNECTIONS(id)
);

CREATE TABLE ACTIVE_CONNECTIONS (
	CONNECTION_ID NUMBER(10,0),
	CONNECTION_DETAILS_ID  NUMBER(10,0) NOT NULL,
	PRIMARY KEY (CONNECTION_ID),
	CONSTRAINT fk_ac_connection
        FOREIGN KEY (CONNECTION_ID)
        REFERENCES CONNECTIONS(id),
    CONSTRAINT fk_ac_connection_details
        FOREIGN KEY (CONNECTION_DETAILS_ID)
        REFERENCES CONNECTIONS_DETAILS(id)
);

CREATE SEQUENCE CONNECTIONS_SEQUENCE START WITH 1;
CREATE SEQUENCE CONNECTIONS_DETAILS_SEQUENCE START WITH 1;

--changeset dinchand:connection_tables_grants dbms:oracle
GRANT UPDATE, INSERT, DELETE, SELECT ON CONNECTIONS TO GCONTACTINGAPI_USER;
GRANT UPDATE, INSERT, DELETE, SELECT ON CONNECTIONS_DETAILS TO GCONTACTINGAPI_USER;
GRANT UPDATE, INSERT, DELETE, SELECT ON ACTIVE_CONNECTIONS TO GCONTACTINGAPI_USER;
GRANT SELECT ON CONNECTIONS_SEQUENCE TO GCONTACTINGAPI_USER;
GRANT SELECT ON CONNECTIONS_DETAILS_SEQUENCE TO GCONTACTINGAPI_USER;

--changeset ayushm:webhook_tables
CREATE TABLE WEBHOOK_CONNECTIONS (
 	ID NUMBER(10,0),
	CONNECTION_TYPE VARCHAR2(255 CHAR) NOT NULL,
	URL VARCHAR2(1000 CHAR) NOT NULL,
	ACCOUNT_ID NUMBER(10,0) NOT NULL,
	IS_ACTIVE NUMBER(1,0) NOT NULL,
	PRIMARY KEY (ID)
);

ALTER TABLE WEBHOOK_CONNECTIONS ADD CONSTRAINT ACTIVE_UNIQUE UNIQUE(ACCOUNT_ID, IS_ACTIVE);
CREATE SEQUENCE WEBHOOK_CONNECTIONS_SEQUENCE START WITH 1;

--changeset ayushm:webhook_tables_grants dbms:oracle
GRANT UPDATE, INSERT, DELETE, SELECT ON WEBHOOK_CONNECTIONS TO GCONTACTINGAPI_USER;
GRANT SELECT ON WEBHOOK_CONNECTIONS_SEQUENCE TO GCONTACTINGAPI_USER;

--changeset ayushm:webhook_tables_update
ALTER TABLE WEBHOOK_CONNECTIONS DROP CONSTRAINT ACTIVE_UNIQUE;

--changeset ayushm:STRY2550282 dbms:oracle
ALTER TABLE ACCOUNT_SETTINGS ADD CAPABILITY VARCHAR(255 CHAR);
ALTER TABLE ACCOUNT_SETTINGS ADD CONSUMERS VARCHAR(255 CHAR);

--changeset ayushm:STRY2799191
CREATE TABLE SURVEY_SETTINGS (
    ID NUMBER(10,0),
    NAME VARCHAR2(255 CHAR) NOT NULL,
    CHANNEL VARCHAR2(255 CHAR) NOT NULL,
    CHANNEL_DIRECTION VARCHAR2(255 CHAR) NOT NULL,
    VOICE_SURVEY_ID VARCHAR2(255 CHAR) NOT NULL,
    CALLFLOW_NAME VARCHAR2(255 CHAR),
    MIN_FREQUENCY NUMBER(10,0),
    DELAY NUMBER(38,0),
    SURVEY_OFFER_RATIO  NUMBER,
    MIN_CONTACT_LENGTH NUMBER,
    SURVEY_FOR_TRANSFERS NUMBER(1,0),
	ACCOUNT_ID NUMBER(10,0) NOT NULL,
	PRIMARY KEY (ID)
);
CREATE TABLE SURVEY_PH_NUM_FORMAT (
    ID NUMBER(10,0),
    SURVEY_ID NUMBER(10,0) NOT NULL,
    FORMAT VARCHAR2(255 CHAR) NOT NULL,
    DIRECTION NUMBER(1,0) NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT FK_SURVEY_FORMAT_SURVEY_ID
        FOREIGN KEY (SURVEY_ID)
            REFERENCES SURVEY_SETTINGS(id)
);
CREATE TABLE SURVEY_ORG_MAPPING (
     ID NUMBER(10,0),
     SURVEY_ID NUMBER(10,0) NOT NULL,
     ORG_ID NUMBER(10,0) NOT NULL,
     PRIMARY KEY (ID),
     CONSTRAINT FK_SURVEY_ORG_SURVEY_ID
        FOREIGN KEY (SURVEY_ID)
            REFERENCES SURVEY_SETTINGS(id)
);
ALTER TABLE SURVEY_ORG_MAPPING ADD CONSTRAINT SurveyOrg_VALUE UNIQUE(SURVEY_ID, ORG_ID);
CREATE TABLE SURVEY_TASKQ_MAPPING (
      ID NUMBER(10,0),
      SURVEY_ID NUMBER(10,0) NOT NULL,
      TASKQUEUE_ID NUMBER(10,0) NOT NULL,
      PRIMARY KEY (ID),
      CONSTRAINT FK_SURVEY_TASKQ_SURVEY_ID
        FOREIGN KEY (SURVEY_ID)
            REFERENCES SURVEY_SETTINGS(id)
);
ALTER TABLE SURVEY_TASKQ_MAPPING ADD CONSTRAINT SurveyTaskQ_VALUE UNIQUE(SURVEY_ID, TASKQUEUE_ID);
CREATE SEQUENCE SURVEY_SETTINGS_SEQUENCE START WITH 1;
CREATE SEQUENCE SURVEY_PH_NUM_FORMAT_SEQUENCE START WITH 1;
CREATE SEQUENCE SURVEY_ORG_MAPPING_SEQUENCE START WITH 1;
CREATE SEQUENCE SURVEY_TASKQ_MAPPING_SEQUENCE START WITH 1;

--changeset ayushm:survey_grant dbms:oracle
GRANT UPDATE, INSERT, DELETE, SELECT ON SURVEY_SETTINGS TO GCONTACTINGAPI_USER;
GRANT UPDATE, INSERT, DELETE, SELECT ON SURVEY_PH_NUM_FORMAT TO GCONTACTINGAPI_USER;
GRANT UPDATE, INSERT, DELETE, SELECT ON SURVEY_ORG_MAPPING TO GCONTACTINGAPI_USER;
GRANT UPDATE, INSERT, DELETE, SELECT ON SURVEY_TASKQ_MAPPING TO GCONTACTINGAPI_USER;
GRANT SELECT ON SURVEY_SETTINGS_SEQUENCE TO GCONTACTINGAPI_USER;
GRANT SELECT ON SURVEY_PH_NUM_FORMAT_SEQUENCE TO GCONTACTINGAPI_USER;
GRANT SELECT ON SURVEY_ORG_MAPPING_SEQUENCE TO GCONTACTINGAPI_USER;
GRANT SELECT ON SURVEY_TASKQ_MAPPING_SEQUENCE TO GCONTACTINGAPI_USER;

--changeset gjcompagner:add_cascades
ALTER TABLE SURVEY_TASKQ_MAPPING DROP CONSTRAINT FK_SURVEY_TASKQ_SURVEY_ID;
ALTER TABLE SURVEY_TASKQ_MAPPING ADD CONSTRAINT FK_SURVEY_TASKQ_SURVEY_ID FOREIGN KEY (SURVEY_ID)
    REFERENCES SURVEY_SETTINGS(id)
    ON DELETE CASCADE;
ALTER TABLE SURVEY_ORG_MAPPING DROP CONSTRAINT FK_SURVEY_ORG_SURVEY_ID;
ALTER TABLE SURVEY_ORG_MAPPING ADD CONSTRAINT FK_SURVEY_ORG_SURVEY_ID FOREIGN KEY (SURVEY_ID)
    REFERENCES SURVEY_SETTINGS(id)
    ON DELETE CASCADE;
ALTER TABLE SURVEY_PH_NUM_FORMAT DROP CONSTRAINT FK_SURVEY_FORMAT_SURVEY_ID;
ALTER TABLE SURVEY_PH_NUM_FORMAT ADD CONSTRAINT FK_SURVEY_FORMAT_SURVEY_ID FOREIGN KEY (SURVEY_ID)
    REFERENCES SURVEY_SETTINGS(id)
    ON DELETE CASCADE;

--changeset pranjut:audit_entity_tables dbms:h2 failOnError:true
CREATE TABLE AUDIT_INFO (
                            ID                BIGINT        AUTO_INCREMENT,
                            MODIFIED_BY       VARCHAR2(255 CHAR)  NOT NULL,
                            MODIFIED_TIME     TIMESTAMP           NOT NULL,
                            PRIMARY KEY       (ID)
);

CREATE TABLE AUDIT_ENTITY (
                              ID                BIGINT        AUTO_INCREMENT,
                              REV_ID        NUMBER(15,0)        NOT NULL,
                              ACCOUNT_ID    NUMBER(15,0),
                              AUDIT_TYPE    VARCHAR2(10 CHAR)   NOT NULL,
                              ENTITY_TYPE   VARCHAR2(255 CHAR)  NOT NULL,
                              ENTITY_ID     VARCHAR2(255 CHAR)  NOT NULL,
                              ENTITY_JSON   CLOB,
                              ENTITY_JSON_DATA   CLOB,
                              PRIMARY KEY   (ID)
);

CREATE UNIQUE INDEX AUDIT_ENTITY_ENTITY_ID_TYPE ON AUDIT_ENTITY (ENTITY_ID, ENTITY_TYPE, ACCOUNT_ID, REV_ID);
CREATE INDEX AUDIT_ENTITY_ACCOUNT_ID ON AUDIT_ENTITY (ACCOUNT_ID, ENTITY_TYPE);
ALTER TABLE AUDIT_ENTITY ADD CONSTRAINT FK_AUDIT_INFO FOREIGN KEY (REV_ID) REFERENCES AUDIT_INFO (ID);

--changeset dinchand:add_better_index dbms:oracle
DROP INDEX ORGANISATION_UNIQUE_IDX;
CREATE UNIQUE INDEX ORGANISATION_UNIQUE_IDX ON ORGANISATIONS (ACCOUNT_ID,PARENT_ID, LOWER(NAME),ORG_LEVEL);

--changeset dinchand:SETTINGS_METADATA dbms:oracle
CREATE TABLE SETTINGS_METADATA (
                                   ID NUMBER(10,0),
                                   NAME VARCHAR2(50 CHAR),
                                   INPUT_TYPE VARCHAR2(255 CHAR),
                                   REGEX VARCHAR2(255 CHAR),
                                   CAPABILITY VARCHAR2(255 CHAR),
                                   CONSUMERS VARCHAR2(255 CHAR),
                                   PRIMARY KEY(ID)
);
CREATE UNIQUE INDEX SETTINGS_NAME_IDX ON SETTINGS_METADATA (NAME);
ALTER TABLE SETTINGS_METADATA ADD CONSTRAINT SETTINGS_METADATA_INPUT_TYPE CHECK ((INPUT_TYPE IN ('RADIO', 'DROPDOWN')) OR (INPUT_TYPE = 'TEXTBOX' AND REGEX IS NOT NULL));

CREATE TABLE SETTINGS_METADATA_OPTIONS ( ID NUMBER(10,0) ,
                                         SETTINGS_META_ID NUMBER(10,0) NOT NULL,
                                         VALUE VARCHAR2(255 CHAR) NOT NULL,
                                         DISPLAY_NAME VARCHAR2(255 CHAR) NOT NULL,
                                         PRIMARY KEY  (ID));

CREATE UNIQUE INDEX SETTINGS_OPTIONS_IDX ON SETTINGS_METADATA_OPTIONS (SETTINGS_META_ID,VALUE);

ALTER TABLE SETTINGS_METADATA_OPTIONS ADD CONSTRAINT FK_SETTINGS_METADATA FOREIGN KEY(SETTINGS_META_ID) REFERENCES SETTINGS_METADATA(ID) ON DELETE CASCADE;

CREATE SEQUENCE SETTINGS_METADATA_SEQUENCE START WITH 1;
CREATE SEQUENCE SETTINGS_METADATA_OPTIONS_SEQUENCE START WITH 1;
GRANT UPDATE, INSERT, DELETE, SELECT ON SETTINGS_METADATA TO GCONTACTINGAPI_USER;
GRANT UPDATE, INSERT, DELETE, SELECT ON SETTINGS_METADATA_OPTIONS TO GCONTACTINGAPI_USER;
GRANT SELECT ON SETTINGS_METADATA_SEQUENCE TO GCONTACTINGAPI_USER;
GRANT SELECT ON SETTINGS_METADATA_OPTIONS_SEQUENCE TO GCONTACTINGAPI_USER;

--changeset dinchand:DISPLAY_ATTR_ORDER dbms:oracle
ALTER TABLE ATTRIBUTES ADD DISPLAY_ORDER NUMBER(5,0);

--changeset ayushm:STRY3872973 dbms:oracle
ALTER TABLE CONNECTIONS_DETAILS ADD REGION VARCHAR(1024 CHAR);

--changeset ayushm:STRY3872973_h2 dbms:h2 failOnError:true
ALTER TABLE CONNECTIONS_DETAILS ADD REGION VARCHAR2(1024 CHAR);

--changeset martine:4910881_boolean_should_not_be_nullable failOnError:true dbms:oracle
UPDATE SURVEY_SETTINGS SET SURVEY_FOR_TRANSFERS = 0 where SURVEY_FOR_TRANSFERS is null;
ALTER TABLE SURVEY_SETTINGS MODIFY (SURVEY_FOR_TRANSFERS NUMBER(1) DEFAULT 0 NOT NULL);
